# Generated by Django 3.2.6 on 2021-08-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('account_number', models.CharField(blank=True, max_length=10, null=True)),
                ('account_type', models.CharField(choices=[('Savings', 'Savings'), ('Current', 'Current'), ('Corporate', 'Corporate')], default='Savings', max_length=20)),
                ('opening_branch', models.CharField(max_length=40)),
                ('opening_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
