# Generated by Django 3.2.6 on 2021-08-02 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBiography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=11)),
                ('house_address', models.CharField(max_length=100)),
                ('account_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.accountuser')),
            ],
        ),
    ]
