# Generated by Django 3.2.6 on 2021-08-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userbiography_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbiography',
            name='account_balance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
