# Generated by Django 3.2.6 on 2021-08-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userbiography_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbiography',
            name='bvn',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
