# Generated by Django 3.2.6 on 2021-08-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userbiography_bvn'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=20)),
                ('transaction_type', models.CharField(max_length=10)),
                ('transaction_date', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField()),
                ('category', models.CharField(max_length=15)),
            ],
        ),
    ]
